### ISSUE TITLE
handler.infect in GIllespie not found

### ISSUE THREAD

**Issue by simondashnash** [junlingm/ABM#1]
Hi
I can't get your Gillespie example to run. Hope you will be able to review.

https://github.com/junlingm/ABM/wiki/Gillespie-SIR

Schedule events:
`reschedule(0, sim$get, sim$state)` get `error unused argument (sim$state)`, which is maybe from an earlier stage in library development as the state now comes from agent.

But if I change it to `reschedule(0, sim$get )` then I get (with debug but without source):
```
Error in reschedule(0, sim$get) : object 'handler.infect' not found
Called from: newEvent(t.inf, handler.infect)
```
and debug (approximate)
```
function (time, handler) 
{
  .Call(`_ABM_newEvent`, time, handler)
}
```

I am using R4.3.2 and ABM 0.3

**Comment by junlingm** [comment]
Indeed. There were two problems:

1. We called "reschedule" too early to initialize the first event. Note that, in side this function, "handler.infect" is called, but it is not defined yet when it is called. 
2. The "reschedule" function only takes two arguments, so the "sim$state" shouldn't be there.

I have edited the page with the following fixes:

1. move the initialization of the first event (this call to reschedule) to right before running the simulation.
2. remove the "sim$state" from this call.

Please check if these fixes work for you.

**Comment by simondashnash** [comment]
Works. Thank you for replying so quickly!
